/*
 * HallInformation.java
 *
 * Created on October 13, 2013, 12:03 AM
 */

package eventmanagementsystem;

/**
 *
 * @author  Dharmendra
 */
public class HallInformation extends javax.swing.JInternalFrame {

    /** Creates new form HallInformation */
    public HallInformation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        comboHall = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Hall Information");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Choose The Hall about which you want to know");

        textArea1.setEditable(false);

        comboHall.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A-2", "A-11", "A-12", "A-13", "EEE Auditorium", "Barn" }));
        comboHall.setName("comboHall"); // NOI18N
        comboHall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboHallItemStateChanged(evt);
            }
        });
        comboHall.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboHallFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(comboHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboHall, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)))
        );

        textArea1.getAccessibleContext().setAccessibleParent(comboHall);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void comboHallFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboHallFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_comboHallFocusLost

private void comboHallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboHallItemStateChanged
// TODO add your handling code here:
    String str;
    str=(String)comboHall.getSelectedItem();
    if(str.compareTo("A-2")==0)
            textArea1.setText("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    else
        textArea1.setText("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
}//GEN-LAST:event_comboHallItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboHall;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

}
